Update version, author and copyright of PDF generated documentation
pmmp/doc.pmmp.io pull request #28
Opened 2021-12-22 13:56 UTC by KygekDev

Will update https://buildmedia.readthedocs.org/media/pdf/pmmp/rtfd/pmmp.pdf

2021-12-22 15:52 UTC, KygekDev commented
I guess time to open this PR.

2022-03-03 17:19 UTC, dktapps requested changes

2022-03-03 17:19 UTC, dktapps commented on source/conf.py
> +   u'dktapps', 'manual'),
```suggestion
   u'PocketMine Team', 'manual'),
```

2022-03-03 17:19 UTC, dktapps commented on source/conf.py
> +     [u'dktapps'], 1)
```suggestion
     [u'PocketMine Team'], 1)
```

2022-03-03 17:19 UTC, dktapps commented on source/conf.py
> +   u'dktapps', 'PocketMine-MPDocs', 'One line description of project.',
```suggestion
   u'PocketMine Team', 'PocketMine-MPDocs', 'One line description of project.',
```

2022-03-04 14:13 UTC, KygekDev commented
I have committed all of your requested changes.

2022-03-04 22:41 UTC, merged

2022-03-05 13:27 UTC, KygekDev commented
Thanks.